### ISSUE TITLE
KeyError: 'choiecs'

### ISSUE THREAD

**Issue by XJ-03** [smthemex/ComfyUI_ChatGLM_API#4]
img2txt节点运行时出现以下问题，api key已经填写了，有空的话麻烦帮忙看一下，谢谢
!!! Exception during processing!!! 'choices'
Traceback (most recent call last):
  File "Z:\SD_ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\SD_ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\SD_ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\SD_ComfyUI\ComfyUI\custom_nodes\ComfyUI_ChatGLM_API\ChatGLM4_API_Node.py", line 275, in zhipuai_img2txt_api
    content_img = img_content["choices"][0]["message"]["content"]
                  ~~~~~~~~~~~^^^^^^^^^^^

**Comment by smthemex** [comment]
已经修复，你再看看。

**Comment by XJ-03** [comment]
> 已经修复，你再看看。

重新拉取后还是不可以... text2text是没问题的，只有图像描述会出现

**Comment by smthemex** [comment]
奇怪，我本地端测试是没有问题的。你试着只用描述此图片来验证。

**Comment by XJ-03** [comment]
> 奇怪，我本地端测试是没有问题的。你试着只用描述此图片来验证。

还是不行... 请问这个对环境有什么要求吗，或者输入图像

**Comment by smthemex** [comment]
最好是更新到最新的diffuser比如0.29以上，但是按理这个跟智谱没关系，cv2 你看看你装了没有

**Comment by XJ-03** [comment]
好的，我再试试，感谢
